---
- name: install LAMP Stack on CentOS8
  hosts: webserver
  become: yes
  vars_files:
    - vars_lamp.yaml
  tasks:
    - name: Installing Apache
      dnf: name=httpd state=latest
    
    - name: Enable httpd service
      systemd: name=httpd state=restarted enabled=yes

    - name: Install Mysql DB and requirements
      dnf:
        name:
          - python3
          - python3-pip
          - mariadb-server
          - mariadb
        state: latest
    
    - name: make sure pymysql is installed
      pip: name=pymysql state=latest
    
    - name: Start and enable Mariadb
      systemd: name=mariadb.service enabled=yes state=started
    
    - name: create a new database
      mysql_db: name=demo state=present
    
    - name: create a database user
      mysql_user:
        name: ansible 
        password: "{{ mysql_passwd }}"
        priv: '*.*:ALL'
        state: present
    
    - name:
      ping:
