---
- name: Prerequisites
  hosts: all
  gather_facts: yes
  tasks:
    - name: Add user ansible - webserver
      when: ansible_facts['distribution'] == "CentOS" 
      user:
        name: ansible
        uid: 2500
        groups: ["wheel"]

    - name: Add public key 
      authorized_key: 
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


    - name: Add user ansible - database
      when: ansible_facts['distribution'] == "Ubuntu" 
      user:
        name: ansible
        uid: 2500
        groups: ["sudo"]
        shell: /bin/bash

    - name: Add public key 
      authorized_key: 
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"